### ISSUE TITLE
Add support for .ini files

### ISSUE THREAD

**Issue by pereorga** [Softcatala/translation-memory-tools#129]
Used in WinSCP for example: https://github.com/winscp/winscp/blob/master/translations/CA.ini

Maybe this could be used? http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/ini2po.html

**Comment by jordimas** [comment]
Hi!

We do support processing of INI files:

https://github.com/Softcatala/translation-memory-tools/blob/master/src/builder/convertfiles.py#L118

What prevents us to add this project is that the INI file only contains translated strings. And in this case we do not have an INI file with the English strings at https://github.com/winscp/winscp/tree/master/translations that we can use to build the English/Catalan string pair.

Jordi

**Comment by pereorga** [comment]
I see.

I have generated the English file:
https://raw.githubusercontent.com/pereorga/software-translations/master/winscp/EN.ini

I have also updated the Catalan version, removing outdated sentences and unnecessary escaping of single quotes, so it matches the generated English file:
https://raw.githubusercontent.com/pereorga/software-translations/master/winscp/CA.ini

I'm happy to keep these files updated or put them elsewhere.

Does this help?

**Comment by jordimas** [comment]
Hi

Yes, it does. 

I added support:

https://github.com/Softcatala/translation-memory-tools/commit/bc9019d6c063ab31ec160085db5bdacaf6e8e298

The question is how we make sure that you github repository stays up to date with upstream.

Jordi,

**Comment by jordimas** [comment]
Cool. Thanks

**Comment by pereorga** [comment]
Thank you!

If there is any issue with that file (line endings, encoding, whatever) let me know.

**Comment by pereorga** [comment]
Hi @jordimas,

Is there a reason why you specified the main github repository rather than the WinSCP PO raw file? I guess this may create conflicts if I add more projects to https://github.com/pereorga/software-translations
