### ISSUE TITLE
Afegir Greenshot i altres amb traducció basada en fitxers XML

### ISSUE THREAD

**Issue by pereorga** [Softcatala/translation-memory-tools#173]
És en un fitxer XML monolingüe: https://github.com/greenshot/greenshot/tree/develop/src/Greenshot/Languages

No em queda clar si podem importar fàcilment fitxers XML així. No trobo exemples dins `cfg/`, però la llista de programes en el que això seria útil és llarga.

**Comment by jordimas** [comment]
Si pots ampliar aquest tiquet amb la llista de programes que això seria útil, és bàsicament per si disseny un sistema que ens assegurem que funciona bé amb tots els casos.

Un primer pas fonamental seria que en un mateix fileset es pogués baixar més d'un fitxer:

https://github.com/Softcatala/translation-memory-tools/blob/master/cfg/projects/Abiword.json#L7

Per exemple, que el camp url fos ulrs i ademetés una llista

**Comment by pereorga** [comment]
Això va quedar oblidat. Crec que podríem mantenir una llista amb els formats que suportem (al README?) i una altra dels formats que ens interessa suportar. Tant de bo cada vegada es tendeixi més a fer servir formats estàndards. Si no, espero que cada vegada existeixin més eines de conversió entre formats

**Comment by pereorga** [comment]
Diferents formats XML monolingüe que he trobat:

- Greenshot (etiquetes `<resource>`) https://github.com/greenshot/greenshot/blob/develop/src/Greenshot/Languages/language-ca-CA.xml

- Notepad++ (etiquetes `<item>`) https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/catalan.xml

- Veracrypt (etiquetes `<entry>`) https://www.veracrypt.fr/code/VeraCrypt/tree/Translations/Language.ca.xml

A més:

- El format XLIFF també és XML i està suportat pel [Translate Toolkit](https://github.com/translate/translate). En les memòries veig que s'utilitza però només com a part de la integració amb crowdwin?

- El format .Net Resource (ResW/ResX) de Microsoft no està suportat, tot i que el suporta [Translate Toolkit](https://github.com/translate/translate). Jo el converteixo pel MS Calc aquí: https://github.com/pereorga/software-translations/blob/master/calc/generate.sh. Si hi hagués suport en les memòries es podria integrar directament, ja que hi ha molts programes que el fan servir, sobretot per Windows.

- El format TMX també és XML i ja està suportat

- El format Qt Linguist (.ts) també és XML i ja està suportat

**Comment by pereorga** [comment]
Un altre format de fitxer XML, en aquest cas bilingüe: 
KeePass (etiquetes `<strings><data>`) https://kumisystems.dl.sourceforge.net/project/keepass/Translations%202.x/2.52/KeePass-2.52-Catalan.zip

**Comment by pereorga** [comment]
Tot i que no és XML, un altre format que ens pot interessar suportar en el futur és [Fluent](https://projectfluent.org/), de Mozilla.

**Comment by pereorga** [comment]
Procedeixo a tancar aquest tiquet. Després de mirar-m'ho, crec que convertir els fitxers XML personalitzats crec que no val la pena. Els exemples descrits, o bé són massa poques cadenes (Greenshot), o l'estructura dels fitxers és molt peculiar (Notepad++, KeePass), o bé no hi ha manera de resoldre quan les cadenes s'han traduït o no, ni potser una manera fàcil d'accedir a les cadenes originals (Veracrypt).

Pot ser interessant suportar (o no) els formats descrits XLIFF, XTB (Anglular XML), ResW/ResX i Fluent, i per això crearé tiquets individuals.
