### ISSUE TITLE
Podeu afegir «fwupd» a freedesktop

### ISSUE THREAD

**Issue by bellaperez** [Softcatala/translation-memory-tools#199]
Hola,

Acabo de traduir unes quantes entrades i en revisar m'adono que no apareix cap informe aquí.

Moltes gràcies per endavant:
https://www.transifex.com/freedesktop/fwupd/language/ca/

**Comment by bellaperez** [comment]
@jordimas Hola. Podeu fer-vos càrrec d'aquesta issue, em vindria bé

**Comment by jordimas** [comment]
Sí, ja ho tens:
https://static.softcatala.org/quality/freedesktop.html

Agafem les traduccions de Github ja que estem intentant reduir les dependències amb Transifex
