### ISSUE TITLE
Incloure les traduccions de VLC per iOS

### ISSUE THREAD

**Issue by pereorga** [Softcatala/translation-memory-tools#263]
Les traduccions d'Android i iOS es poden incloure, però han d'estar en una estructura de directoris específica.

_Originally posted by @jordimas in https://github.com/Softcatala/translation-memory-tools/issues/262#issuecomment-1653199544_

**Comment by pereorga** [comment]
Android s'afegeix aquí: https://github.com/Softcatala/translation-memory-tools/pull/276

iOS no funciona:

```
        "VLC-ios": {
            "url": "https://code.videolan.org/videolan/vlc-ios.git",
            "type": "git"
        },
```

```
root: WARNING: trying to parse /var/folders/ls/d7rgrlcn5ln134pbkk3swnqm0000gn/T/tmp6o6hg19e/Resources/ca.lproj/Localizable.strings with encoding: utf-8 but detected encoding is utf-16 (confidence: 1.0)
prop2po: WARNING: Error processing: input /var/folders/ls/d7rgrlcn5ln134pbkk3swnqm0000gn/T/tmp6o6hg19e/Resources/ca.lproj/Localizable.strings, output /var/folders/ls/d7rgrlcn5ln134pbkk3swnqm0000gn/T/tmp6o6hg19e/ca-apple-0.po, template /var/folders/ls/d7rgrlcn5ln134pbkk3swnqm0000gn/T/tmp6o6hg19e/Resources/en.lproj/Localizable.strings: Cannot detect encoding for /var/folders/ls/d7rgrlcn5ln134pbkk3swnqm0000gn/T/tmp6o6hg19e/Resources/ca.lproj/Localizable.strings.
[###########################################] 100%
ERROR:root:Project VLC media player, fileset VLC-ios, words -1
```


He aconseguit convertir els fitxers iOS així:

```
iconv -f UTF-16LE -t UTF-8 Resources/ca.lproj/Localizable.strings > Localizable.utf8.strings
prop2po -t Resources/en.lproj/Localizable.strings -i Localizable.utf8.strings --encoding=utf-8 
````

Cap altra opció de `prop2po` sembla funcionar, `iconv` és necessari. Suposo que es podria especificar la codificació del fitxer català (l'anglès és ASCII i no cal) al fitxer JSON del projecte i processar-lo amb `iconv` o equivalent, o intentar detectar la codificació (p. ex. amb `file Resources/ca.lproj/Localizable.strings | grep -q 'UTF-16'`)

**Comment by jordimas** [comment]
En la meva opinió és un bug del translate-toolkit que no suporta aquest tipus d'encoding. Jo els hi obriria un bug amb ells a veure si ho solucionen.

**Comment by pereorga** [comment]
Creat: https://github.com/translate/translate/issues/4989
