### ISSUE TITLE
`pattern` no funciona correctament

### ISSUE THREAD

**Issue by pereorga** [Softcatala/translation-memory-tools#359]
```
git remote add pere https://github.com/pereorga/translation-memory-tools
git fetch --all
git checkout feat/keycloak
cd src/
python3 builder.py -pKeycloak
```

Resultat:

- S'importen totes les cadenes de https://github.com/pereorga/software-translations

Resultat esperat:

- S'haurien d'importar les cadenes de https://github.com/pereorga/software-translations/tree/master/keycloak/translations

És a dir, sembla que el `pattern` no funciona correctament:

```
{
    "project": "Keycloak",
    "license": "Apache-2.0",
    "projectweb": "https://github.com/keycloak/keycloak",
    "softcatala": true,
    "fileset": {
        "Keycloak": {
            "url": "https://github.com/pereorga/software-translations.git",
            "type": "git",
            "duplicates": "msgctxt",
            "pattern": ".*?/keycloak/.*?"
        }
    }
}
```

**Comment by jordimas** [comment]
Hola Pere. A mi només s'importen les cadenes keycloak:

_Adding file: /tmp/Keyclo_ngpuo61s/keycloak/translations/account.po to translation memory with 1509 words
Adding file: /tmp/Keyclo_ngpuo61s/keycloak/translations/account_v2.po to translation memory with 685 words
Adding file: /tmp/Keyclo_ngpuo61s/keycloak/translations/admin.po to translation memory with 617 words
Adding file: /tmp/Keyclo_ngpuo61s/keycloak/translations/email.po to translation memory with 725 words
Adding file: /tmp/Keyclo_ngpuo61s/keycloak/translations/login.po to translation memory with 2668 words_

El que si és cert és que el pattern s'aplica després de la conversió i que alguns cops (per exemple, si hi ha patterns de directori) es converteixen fitxers que després no s'usen.

**Comment by pereorga** [comment]
Entenc que no s'acaben important, doncs, que només es processen.
